name: Sync Upstream Release

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Latest Release
        id: get_latest_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/hjdhnx/drpy-node/releases/latest)
          echo "::set-output name=tag::[${{ github.event_name }}]"
          echo "::set-output name=zip_url::["${{ steps.get_latest_release.outputs.tag }}"].zip"

      - name: Download Latest Release
        run: |
          curl -L -o drpy-node.7z [${{ steps.get_latest_release.outputs.zip_url }}]

      - name: Extract 7z File
        run: |
          sudo apt-get install p7zip-full
          7z x drpy-node.7z

      - name: Create ZIP File
        run: |
          zip -r drpy-node.zip ./

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ steps.get_latest_release.outputs.tag }}
          files: drpy-node.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
